# Generated by Django 3.1.2 on 2020-10-23 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=64)),
                ('Body', models.TextField()),
                ('Status', models.CharField(choices=[('v', 'ویژه'), ('f', 'پیش نویس'), ('d', 'درانتظار تایید'), ('p', 'منتشر شده')], max_length=1)),
                ('Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Photo', models.ImageField(upload_to='pic-blog')),
                ('Category', models.ManyToManyField(to='blog.Cat_org')),
            ],
        ),
    ]
