# Generated by Django 3.1.2 on 2020-10-24 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat_org',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'وبلاگ', 'verbose_name_plural': 'بلاگ ها'},
        ),
        migrations.AddField(
            model_name='posts',
            name='Author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='نویسنده'),
            preserve_default=False,
        ),
    ]
